version: '2.1'
services:
  demo:
    labels:
     - "is_top_app=0"
     - "description=Management front-end and back-end (simulated back-end management scripts)"
    build: .
    image: hilbert/mng:${IMAGE_VERSION:-latest}
    network_mode: host
    privileged: false
    stdin_open: false
    tty: false
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - "${HILBERT_SERVER_CONFIG_SSH_PATH:-~/.ssh}:/root/SSH:ro"
     - /tmp:/tmp:rw
     - "${HILBERT_SERVER_CONFIG_PATH:-./}:/HILBERT:ro"
    environment:
     - HOME=/root
     - HILBERT_CLI_PATH=/usr/local/bin
     - HILBERT_SERVER_CONFIG_PATH=/HILBERT/Hilbert.yml
     - HILBERT_SERVER_CONFIG_SSH_PATH=/root/SSH
    entrypoint:
     - /sbin/my_init
     - --skip-runit
     - --skip-startup-files
     - --
#    ports:
#     - "8888:8000"
    expose: 
     - 8000
    restart: always
    command:
     - /usr/local/run.sh
     - --test=1

  mng:
    extends: 
      service: demo
    labels:
     - "description=Management front-end and back-end (real management scripts)"
    restart: on-failure:5
    command:
     - /usr/local/run.sh

