version: '2.0'
services:
  demo:
    labels:
     - "is_top_app=1"
     - "description=Management front-end and back-end (simulated back-end management scripts)"
    build: .
    image: malex984/dockapp:mng
    privileged: false
    stdin_open: false
    tty: false
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - "${PWD}/dockapp_dashboard:/usr/local/dockapp_dashboard:ro"
    entrypoint:
    - /sbin/my_init
    - --skip-runit
    - --skip-startup-files
    - --
    expose:
     - "8080"
    restart: always
    command:
     - /usr/local/bin/run.sh
     - --test=true

  mng:
    extends: 
      service: demo
    labels:
     - "description=Management front-end and back-end (real management scripts)"
    restart: on-failure:5
    volumes:
    - /tmp:/tmp:rw
    - "${HOME}/.ssh:/root/.ssh:ro"  
    - "${HOME}:${HOME}:ro"
    - "${PWD}:/DOCKAPP:rw"
    - "${PWD}/dockapp_dashboard/server/log:/usr/local/dockapp_dashboard/server/log:rw"
    environment:
      CFG_DIR: /DOCKAPP
    working_dir: /DOCKAPP
    command:
    - /DOCKAPP/run.sh
  
