version: '2.0'
services:
  demo:
    labels:
     - "is_top_app=1"
     - "description=Management front-end and back-end (simulated back-end management scripts)"
    build: .
    image: hilbert/mng
    network_mode: host
    privileged: false
    stdin_open: false
    tty: false
    volumes:
    - /etc/localtime:/etc/localtime:ro
    entrypoint:
    - /sbin/my_init
    - --skip-runit
    - --skip-startup-files
    - --
    expose:
     - "8080"
    restart: always
    command:
     - /usr/local/run.sh
     - --log_level=verbose
     - --test=true

  mng:
    extends: 
      service: demo
    labels:
     - "description=Management front-end and back-end (real management scripts)"
    restart: on-failure:5
    command:
     - /usr/local/run.sh
     - --log_level=debug
     - --test=false 
     - --hilbert_cli_path=/usr/local/hilbert-cli/server

