version: '2.1'
services:
  meshcommander:
    labels:
     - "is_top_app=0"
     - "description=Manageability Commander: interact with Intel AMT within a browser"
    build: .
    image: hilbert/meshcommander:${IMAGE_VERSION:-latest}
    network_mode: host
    privileged: false
    stdin_open: false
    tty: false
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /tmp:/tmp:rw
    entrypoint:
     - /sbin/my_init
     - --skip-runit
     - --skip-startup-files
     - --
    expose: 
     - 3000
    restart: on-failure:5
    command:
     - /usr/local/bin/runmeshcmdr.sh

